---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    rails-master-key: AgByakpFtPtzGnER2WeWOndg3h1gSgD9BXYPfgUaOz5VN9Fva42VbjoMPu4ezd93lXIPa+RouXQI8lQVkMdVn8W0yHl44mzYXTDdR+aRUZshplhNSf2stjACl05vLWp3fS5nirnYna8yFDA/zdR8QskWXJnOuR70QRcA5taG5V3PgA1WfDPvAnr01o+MK09THw0Ei4+xMX/+fSf+H8MRjJ4D1xi6sXlaUgqEegEbspjuWUzzRAYQL5mxt4SU7tRLxDsAV5WpWLeBJX2n6gyzgkKQIMiHnyvH36ePSpgFoWeuCCvLPy7+kyCeXqUUoiQ2XAMcQyq2gGFlXetGlPQhAOytyjPW21Y1RXyJG0yRULMDwwI3UE+YTAsU/YYs1+SDChqLBW1ANjanapbm7+ubB6KbTSkuHqilCwcEsb+gx+R6Zx+DxDN6S4eS2+cVOBQIF0CjeChe+CKeyWp6mE9A+EGM9cbca6zmz8ZV3uOKLuzPMQkdffHtOCy4iUQS+08ekkbq2CSLudA62b2KyyAz9UecgzNCVFFXMcT2Rm8WjhKYv5/owI+Ll9b4ojYJsDkl6y4sT5DWJNlkFKF05J4IJRXc//GA3Uo3kduRCVVBrUmkvYOMzL4kFZF1xs/1fs+FvyiS9E/HMFPUbYqO61eGWFm7bAfkr/yfWk0Bz88NcJPf0I7SIXNEvriGUuTd2DBpKHjyniOqLCbVhRTJEj8lPsV20sHhON062HN8vJ+wulF4gg==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
